.Dd February 23, 2025
.Dt BATPER 1
.Os
.
.Sh NAME
.Nm batper
.Nd show batteries' percentage
.
.Sh SYNOPSIS
.Nm
.
.Sh DESCRIPTION
.Nm
prints battery number
with percentage on each line.
.
.Sh EXAMPLES
Your call will look like this:
.Bd -literal -offset indent
$ batper
0 100
1 100
.Ed
.
.Sh SEE ALSO
.Xr apm 8 ,
.Xr sysctl 8
