.Dd March 12, 2025
.Dt TODO 7
.Os batper
.
.Sh NAME
.Nm TODO
.Nd some things
I have to do
but maybe later
.
.Sh SYNOPSIS
.Nm Implement
ports to other systems
.
.Sh DESCRIPTION
.Bl -tag -width Ds -compact
.It Implement ports to other systems
I'd like to add
.Xr batper 1
to my
.Xr dwm 1
bar,
but it has to be
more cross-platform
for this
as I also use Linux.
.El
